name: Notify New Comment

# Controls when the action will run
on:
  issue_comment:
    types: [created]

# Limit the GITHUB_TOKEN permissions
permissions: {}

jobs:
  notify:
    runs-on: ubuntu-latest

    #if: ${{ !github.event.issue.pull_request && !contains(fromJSON('["Jay2113"]'), github.event.comment.user.login) }}

    steps:
      # Runs a single command using the runners shell
      - name: Run webhook curl command
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_COMMENT_WEBHOOK_URL }}
          # GITHUB_CONTEXT: ${{toJson(github)}}
          COMMENT: ${{toJson(github.event.comment.body)}}
        shell: bash
        run: echo $COMMENT | sed 's/\\\n/. /g; s/\\\r//g; s/[^a-zA-Z0-9 &().,:]//g' | xargs -I {} curl -s POST "$WEBHOOK_URL" -H "Content-Type:application/json" --data '{"comment":"{}", "commentUrl":"${{github.event.comment.html_url}}", "commentAuthor":"${{github.event.comment.user.login}}", "issueUrl":"${{github.event.issue.html_url}}", "commentCreateTime":"${{github.event.comment.created_at}}", "commentCount":"${{github.event.issue.comments}}", "issueNumber":"${{github.event.issue.number}}", "reactionCount":"${{github.event.issue.reactions.total_count}}"}'
