name: "Close Stale Issues"

# Controls when the action will run.
on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  cleanup:
    permissions:
      issues: write
      contents: read
    runs-on: ubuntu-latest
    name: Stale issue job
    steps:
      - uses: aws-actions/stale-issue-cleanup@v3
        with:
          # Setting messages to an empty string will cause the automation to skip that category.
          stale-issue-message: This issue has not received a response in a while. If you want to keep this issue open, please leave a comment below and auto-close will be canceled.

          # These labels are required
          stale-issue-label: closing-soon
          exempt-issue-labels: no-autoclose
          response-requested-label: response-requested

          # Don't set closed-for-staleness label to skip closing very old issues regardless of label.
          closed-for-staleness-label: closed-for-staleness

          # Issue timing
          days-before-stale: 1
          days-before-close: 1
          # An "upvote" is the total number of +1, heart, hooray, and rocket reactions on an issue.
          minimum-upvotes-to-exempt: 3

          # Testing/debugging options
          loglevel: DEBUG
          # Set dry-run to true to not perform label or close actions.
          dry-run: false

          repo-token: ${{ secrets.GITHUB_TOKEN }}
